/* === MISSION COMMAND CONFIGURATION: edit these values to personalise the site. === */
const config={commanderName:"ME",location:"TO BE DECIDED",movieDate:"TO BE DECIDED",countdownDate:"2026-07-31T13:00:00",invitationMessage:"A new adventure is approaching, and one trusted agent is required.",cinemas:["Cinema 1","Cinema 2","Cinema 3","Decide later"],schedules:["Opening day","Weekend","Evening schedule","Decide later"],snacks:["Popcorn","Nachos","Fries","No snack","Surprise me"],systemMessages:["Searching for nearby cinemas...","Calculating snack requirements...","Checking multiverse stability...","Tracking friendly neighborhood activity...","Waiting for Agent confirmation...","Analyzing available seats...","Scanning for spoilers...","Mission conditions appear favorable..."],copyTemplate:"Mission accepted! Agent {name} is ready to watch Spider-Man: Brand New Day."};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let state={name:"",id:"",sound:true,sequence:[],input:[],decline:0},audio;
const store=()=>localStorage.setItem("bndMission",JSON.stringify({name:state.name,id:state.id,choices:getChoices(),response:localStorage.getItem("bndResponse")}));
const saved=()=>{try{return JSON.parse(localStorage.getItem("bndMission"))||{}}catch{return{}}};
function show(id){$$('.stage').forEach(x=>x.classList.remove('active'));$('#dashboard').hidden=true;$(id).classList.add('active')}
function randId(){return `SRD-${Math.floor(100+Math.random()*900)}-${Math.floor(10+Math.random()*90)}`}
function beep(f=480,d=.05){if(!state.sound)return;try{audio??=new(window.AudioContext||webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function soundFile(file){if(!state.sound)return;const a=new Audio(`assets/${file}`);a.play().catch(()=>beep())}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function boot(){let messages=['BOOTING STRATEGIC INTELLIGENCE NETWORK...','CONNECTING TO SECURE SERVER...','ENCRYPTION PROTOCOL ACTIVE...','SEARCHING FOR AUTHORIZED AGENT...'],n=0,p=0;let typing=()=>{$('#bootMessage').textContent=messages[n];if(n<messages.length-1)setTimeout(()=>{n++;typing()},700)};typing();let timer=setInterval(()=>{p=Math.min(100,p+Math.ceil(Math.random()*4));$('#bootPercent').textContent=`${String(p).padStart(3,'0')}%`,$('#bootBar').style.width=`${p}%`,$('#bootLog').textContent=config.systemMessages[Math.floor(Math.random()*config.systemMessages.length)];if(p===100){clearInterval(timer);$('#bootTitle').textContent='UNKNOWN AGENT DETECTED';$('#beginIdentity').classList.remove('hidden')}},70);$('#skipBoot').onclick=()=>{clearInterval(timer);$('#bootPercent').textContent='100%';$('#bootBar').style.width='100%';$('#bootTitle').textContent='UNKNOWN AGENT DETECTED';$('#beginIdentity').classList.remove('hidden')}}
function startLogin(){show('#login');$('#generatedId').textContent=state.id||randId();$('#currentDate').textContent=new Date().toLocaleString();setTimeout(()=>$('#agentInput').focus(),200)}
function scanning(){show('#scan');$('#verifyGame').classList.add('hidden');$('#scanEnd').classList.add('hidden');let steps=['SCANNING BIOMETRIC SIGNATURE...','ANALYZING AGENT PROFILE...','VERIFYING MULTIVERSE CLEARANCE...','CHECKING HEROIC POTENTIAL...','IDENTITY CONFIRMED.'],p=0;let timer=setInterval(()=>{p=Math.min(100,p+4);$('#scanPercent').textContent=`${String(p).padStart(3,'0')}%`,$('#scanBar').style.width=`${p}%`,$('#scanTitle').textContent=steps[Math.min(4,Math.floor(p/22))];if(p>=30&&$('#scanResults').children.length<6){['Identity Match: Confirmed','Threat Level: Low','Loyalty Status: Trusted','Heroic Potential: 98%','Snack Compatibility: Excellent','Movie Partner Status: Recommended'].forEach(x=>$('#scanResults').insertAdjacentHTML('beforeend',`<li>${x}</li>`))}if(p===100){clearInterval(timer);$('#scanEnd').textContent=`AGENT ${state.name.toUpperCase()} VERIFIED`;$('#scanEnd').classList.remove('hidden');setTimeout(beginGame,1000)}},85)}
function beginGame(){const game=$('#verifyGame');game.classList.remove('hidden');state.sequence=Array.from({length:3},()=>Math.floor(Math.random()*4));state.input=[];$('#gameMessage').textContent='Observe the three-symbol sequence.';let i=0;const demo=setInterval(()=>{let b=$(`[data-symbol="${state.sequence[i]}"]`);b.classList.add('lit');beep(580+i*70,.08);setTimeout(()=>b.classList.remove('lit'),300);if(++i===3){clearInterval(demo);$('#gameMessage').textContent='Your turn: repeat the sequence.'}},650)}
function gameClick(e){let value=+e.currentTarget.dataset.symbol;if(!state.sequence.length)return;state.input.push(value);e.currentTarget.classList.add('lit');setTimeout(()=>e.currentTarget.classList.remove('lit'),180);if(value!==state.sequence[state.input.length-1]){state.input=[];$('#gameMessage').textContent='SEQUENCE INCORRECT — TRY AGAIN';toast('Sequence incorrect — try again');setTimeout(beginGame,900);return}if(state.input.length===3){$('#gameMessage').textContent='SECURITY SEQUENCE ACCEPTED';setTimeout(granted,700)}}
function granted(){show('#granted');$('#grantWelcome').textContent=`WELCOME, AGENT ${state.name.toUpperCase()}`;soundFile('access-sound.mp3')}
function dashboard(){ $$('.stage').forEach(x=>x.classList.remove('active'));$('#dashboard').hidden=false;document.body.scrollTop=0;document.documentElement.scrollTop=0;fillDashboard(); }
function fillDashboard(){let welcome=`Welcome, Agent ${state.name}.`;$('#navAgent').textContent=state.name.toUpperCase();$('#navId').textContent=state.id;$('#dashWelcome').textContent=welcome;$('#commanderName').textContent=config.commanderName;$('#selectedAgent').textContent=state.name;$('#locationName').textContent=config.location;$('#movieDate').textContent=config.movieDate;$('#personalBrief').textContent=`Agent ${state.name}, you have been selected for this mission.`;$('#briefQuote').textContent=`“Agent ${state.name}, your presence has been specifically requested for this operation. The mission involves entering the cinema, securing excellent seats, obtaining the necessary snacks, and witnessing the beginning of Spider-Man’s brand-new chapter.”`;$('#decisionTitle').textContent=`AGENT ${state.name.toUpperCase()}, WILL YOU JOIN ME TO WATCH SPIDER-MAN: BRAND NEW DAY?`;fillSelect('#cinemaSelect',config.cinemas);fillSelect('#scheduleSelect',config.schedules);fillSelect('#snackSelect',config.snacks);let s=saved().choices||{};$('#cinemaSelect').value=s.cinema||config.cinemas[0];$('#scheduleSelect').value=s.schedule||config.schedules[0];$('#snackSelect').value=s.snack||config.snacks[0];updateChoices();}
function fillSelect(id,items){let select=$(id);select.innerHTML=items.map(x=>`<option>${x}</option>`).join('')}
function getChoices(){return{cinema:$('#cinemaSelect')?.value||config.cinemas[0],schedule:$('#scheduleSelect')?.value||config.schedules[0],snack:$('#snackSelect')?.value||config.snacks[0]}}
function updateChoices(){let c=getChoices(),chosen=[c.cinema,c.schedule,c.snack].filter(x=>!x.toLowerCase().includes('decide')).length,percent=20+chosen*20+(localStorage.getItem('bndResponse')==='accepted'?20:0);$('#readinessValue').textContent=`${percent}%`;$('#readinessBar').style.width=`${percent}%`;let items=['Accept mission invitation','Select preferred cinema','Choose a movie schedule','Select preferred snack','Confirm mission readiness'];$('#checklist').innerHTML=items.map((x,i)=>`<p class="${(i===0&&localStorage.getItem('bndResponse')==='accepted')||i>0&&i<=chosen+1?'done':''}">${x}</p>`).join('');store()}
function decrypt(){let p=0,msg=['Breaking encryption layer 1…','Accessing cinema database…','Analyzing Spider-Verse activity…','Locating mission target…','Mission file decrypted.'];$('#decrypt').disabled=true;let t=setInterval(()=>{p=Math.min(100,p+5);$('#decryptBar').style.width=`${p}%`;$('#decryptText').textContent=msg[Math.min(4,Math.floor(p/22))];if(p===100){clearInterval(t);setTimeout(()=>{$('#lockedFile').classList.add('hidden');$('#mission').classList.remove('hidden');$('#choices').classList.remove('hidden');$('#mission').scrollIntoView({behavior:'smooth'})},500)}},90)}
function finalResponse(type){let accept=type==='accepted';localStorage.setItem('bndResponse',type);store();$('#response').hidden=false;$('#response').classList.toggle('declined',!accept);$('#responseTag').textContent=accept?'TRANSMISSION COMPLETE':'STATUS UPDATE';$('#responseTitle').textContent=accept?'MISSION ACCEPTED':'MISSION DECLINED';$('#responseCopy').innerHTML=accept?`AGENT PARTNERSHIP CONFIRMED<br>Welcome to the mission, Agent ${state.name}.<br>You and ${config.commanderName} are officially assigned to Operation: Brand New Day.<br>Further cinema, date, and time details will be transmitted soon.`:`Agent ${state.name} has declined Operation: Brand New Day.<br>The classified file will remain available if you reconsider.`;let c=getChoices();$('#summary').innerHTML=accept?`AGENT: <b>${state.name}</b><br>AGENT ID: <b>${state.id}</b><br>CINEMA: ${c.cinema}<br>SCHEDULE: ${c.schedule}<br>SNACK: ${c.snack}<br>RESPONSE: <b>MISSION ACCEPTED</b><br>ACCEPTED: ${new Date().toLocaleString()}`:'';$('#responseActions').innerHTML=accept?'<button id="downloadCard" class="primary">DOWNLOAD MISSION CARD</button><button id="copyResponse" class="secondary">COPY RESPONSE</button><button id="returnDash" class="secondary">RETURN TO DASHBOARD</button><button id="restart" class="secondary">RESTART EXPERIENCE</button>':'<button id="reconsider" class="primary">RECONSIDER MISSION</button><button id="returnDash" class="secondary">RETURN TO DASHBOARD</button>';if(accept){confetti();soundFile('mission-accepted.mp3');$('#missionStatus').textContent='MISSION ACCEPTED';$('#missionStatus').className='safe';updateChoices()}bindResponse()}
function bindResponse(){$('#returnDash')?.addEventListener('click',()=>{$('#response').hidden=true});$('#reconsider')?.addEventListener('click',()=>{$('#response').hidden=true;localStorage.removeItem('bndResponse');updateChoices();$('#decision').scrollIntoView({behavior:'smooth'})});$('#restart')?.addEventListener('click',reset);$('#downloadCard')?.addEventListener('click',downloadCard);$('#copyResponse')?.addEventListener('click',copyResponse)}
function copyResponse(){let text=config.copyTemplate.replace('{name}',state.name);navigator.clipboard?.writeText(text).then(()=>toast('Response copied to clipboard.')).catch(()=>manual(text))||manual(text)}function manual(t){let p=$('#manualCopy');p.textContent=t;p.classList.remove('hidden');p.focus();toast('Copy the displayed message manually.')}
function downloadCard(){let c=document.createElement('canvas'),x=c.getContext('2d'),ch=getChoices();c.width=1200;c.height=700;x.fillStyle='#04111f';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#43d9ff';x.lineWidth=8;x.strokeRect(28,28,1144,644);x.fillStyle='#43d9ff';x.font='42px sans-serif';x.fillText('STRATEGIC RESPONSE DIVISION',85,115);x.fillStyle='#56f5a7';x.font='bold 82px sans-serif';x.fillText('MISSION ACCEPTED',85,235);x.fillStyle='#dceaf3';x.font='38px sans-serif';['OPERATION: BRAND NEW DAY',`AGENT: ${state.name} // ${state.id}`,`CINEMA: ${ch.cinema}`,`SCHEDULE: ${ch.schedule}`,`SNACK: ${ch.snack}`,`ACCEPTED: ${new Date().toLocaleString()}`].forEach((t,i)=>x.fillText(t,85,320+i*55));let a=document.createElement('a');a.download='operation-brand-new-day-mission-card.png';a.href=c.toDataURL('image/png');a.click()}
function confetti(){let c=$('#confetti'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let p=Array.from({length:90},()=>({x:c.width/2,y:c.height/2,vx:(Math.random()-.5)*14,vy:(Math.random()-.7)*13,c:Math.random()>.5?'#56f5a7':'#43d9ff'})),f=0;(function d(){x.clearRect(0,0,c.width,c.height);p.forEach(q=>{q.x+=q.vx;q.y+=q.vy;q.vy+=.2;x.fillStyle=q.c;x.fillRect(q.x,q.y,5,5)});if(f++<150)requestAnimationFrame(d)})()}
function reset(){localStorage.removeItem('bndMission');localStorage.removeItem('bndResponse');location.reload()}
function countdown(){let d=Math.max(0,new Date(config.countdownDate)-Date.now()),v=[Math.floor(d/864e5),Math.floor(d/36e5)%24,Math.floor(d/6e4)%60,Math.floor(d/1e3)%60],l=['D','H','M','S'];$('#countdown').innerHTML=v.map((n,i)=>`<span><b>${String(n).padStart(2,'0')}</b>${l[i]}</span>`).join('')}
function extras(){setInterval(()=>{$('#navClock').textContent=new Date().toLocaleTimeString();$('#systemLog').textContent=config.systemMessages[Math.floor(Math.random()*config.systemMessages.length)]},1600);setInterval(countdown,1000);$('#seatGrid').innerHTML=Array.from({length:35},(_,i)=>`<i class="${Math.random()>.63?'off':''}"></i>`).join('');$('#poster').onerror=()=>$('.poster-wrap').classList.add('fallback');$('.poster-wrap').addEventListener('mousemove',e=>{let r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`rotateY(${(e.clientX-r.left-r.width/2)/18}deg) rotateX(${-(e.clientY-r.top-r.height/2)/18}deg)`});$('.poster-wrap').addEventListener('mouseleave',e=>e.currentTarget.style.transform='')}
function particles(){let c=$('#particles'),x=c.getContext('2d'),p=[];function size(){c.width=innerWidth;c.height=innerHeight;p=Array.from({length:55},()=>({x:Math.random()*c.width,y:Math.random()*c.height,v:.15+Math.random()*.4}))}function draw(){x.clearRect(0,0,c.width,c.height);x.fillStyle='#43d9ff';p.forEach(a=>{a.y-=a.v;if(a.y<0)a.y=c.height;x.fillRect(a.x,a.y,1.5,1.5)});requestAnimationFrame(draw)}addEventListener('resize',size);size();draw()}
function init(){let old=saved();state.name=old.name||'';state.id=old.id||randId();particles();boot();extras();if(old.name){show('#returning');$('#returnWelcome').textContent=`Welcome back, Agent ${old.name}.`;$('#returnStatus').textContent=`MISSION STATUS: ${(localStorage.getItem('bndResponse')||'PENDING').toUpperCase()}`}$('#beginIdentity').onclick=startLogin;$('#continueMission').onclick=dashboard;$('#newIdentity').onclick=()=>{localStorage.clear();state.name='';state.id=randId();startLogin()};$('#identityForm').onsubmit=e=>{e.preventDefault();let name=$('#agentInput').value.trim();if(!name){$('#loginError').textContent='IDENTITY CANNOT BE EMPTY';$('.login-layout').classList.add('shake');setTimeout(()=>$('.login-layout').classList.remove('shake'),400);return}state.name=name;state.id=$('#generatedId').textContent;store();scanning()};$$('#symbols button').forEach(b=>b.onclick=gameClick);$('#bypassGame').onclick=granted;$('#openDashboard').onclick=dashboard;$('#decrypt').onclick=decrypt;$('#accept').onclick=()=>finalResponse('accepted');$('#decline').onclick=()=>{if(matchMedia('(hover:none)').matches&&state.decline<3){$('#decline').textContent=['Are you sure?','The multiverse needs us.','Spider-Man is counting on you.'][state.decline++];return}finalResponse('declined')};$('#decline').onmouseenter=()=>{if(matchMedia('(hover:hover)').matches&&state.decline++<2){$('#decline').style.transform=`translate(${state.decline===1?'-45px':'45px'},${state.decline===1?'-10px':'8px'})`;setTimeout(()=>$('#decline').style.transform='',500)}};$$('#cinemaSelect,#scheduleSelect,#snackSelect').forEach(e=>e.onchange=updateChoices);$('#soundToggle').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'♫':'♩';e.currentTarget.setAttribute('aria-pressed',state.sound);beep(620)};$('#reset').onclick=reset;$('.mission-notice button').onclick=()=>$('.mission-notice').remove();addEventListener('mousemove',e=>{$('.cursor-glow').style.left=e.clientX+'px';$('.cursor-glow').style.top=e.clientY+'px'});addEventListener('keydown',e=>{if(e.key==='Enter'&&$('#boot').classList.contains('active')&& !$('#beginIdentity').classList.contains('hidden'))startLogin();if(e.key==='Escape')$('#response').hidden=true;if(e.key.toLowerCase()==='s'&&e.ctrlKey){e.preventDefault();toast('SPIDER-SENSE ACTIVATED');$('.dashboard').classList.add('sense');setTimeout(()=>$('.dashboard').classList.remove('sense'),1300)}})}
document.addEventListener('DOMContentLoaded',init);

/* Optional self-contained audio bed: uses Web Audio, so no music file is required. */
let atmosphere,atmosphereTimer;
function playEffect(frequency=520,duration=.1,type='sine'){
	if(!state.sound)return;
	try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(frequency,audio.currentTime);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}
}
function toggleAtmosphere(){
	if(atmosphere){atmosphere.forEach(node=>node.stop());clearInterval(atmosphereTimer);atmosphere=null;return}
	try{audio??=new(window.AudioContext||window.webkitAudioContext)();const master=audio.createGain();master.gain.value=.032;master.connect(audio.destination);const droneGain=audio.createGain();droneGain.gain.value=.26;droneGain.connect(master);atmosphere=[55,82.41,110].map((frequency,index)=>{const oscillator=audio.createOscillator();oscillator.type=index===1?'sine':'triangle';oscillator.frequency.value=frequency;oscillator.detune.value=index===2?7:0;oscillator.connect(droneGain);oscillator.start();return oscillator});let note=0,pattern=[55,55,82.41,110,73.42,82.41,55,110];const pulse=()=>{const oscillator=audio.createOscillator(),gain=audio.createGain(),time=audio.currentTime;oscillator.type='square';oscillator.frequency.setValueAtTime(pattern[note++%pattern.length],time);gain.gain.setValueAtTime(.001,time);gain.gain.linearRampToValueAtTime(.18,time+.015);gain.gain.exponentialRampToValueAtTime(.001,time+.26);oscillator.connect(gain).connect(master);oscillator.start(time);oscillator.stop(time+.28);if(note%8===0)playEffect(920,.22,'sine')};pulse();atmosphereTimer=setInterval(pulse,330);playEffect(740,.16,'triangle')}catch{}
}
document.addEventListener('DOMContentLoaded',()=>{
	document.addEventListener('pointerdown',()=>toggleAtmosphere(),{once:true});
	document.addEventListener('pointerover',event=>{if(event.target.closest('button,.primary,.secondary'))playEffect(330,.035,'square')});
	document.addEventListener('click',event=>{if(event.target.closest('.primary'))playEffect(760,.11,'triangle');else if(event.target.closest('.secondary'))playEffect(250,.08,'sine')});
});
